markdown: kramdown
highlighter: rouge

title: Composita
logo: /assets/img/icons/composita-icon-512x512.png

name: Composita
description: Composita Programming Language
url: https://www.composita.dev/

